matrix:
  include:
    language: node_js
    node_js:
      - '6.9.1'
      - '7.0.0'
    sudo: false

    addons:
      apt:
        packages:
          - xvfb

    install:
      - export DISPLAY=':99.0'
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - npm install
    
    
    language: python
    python: 
      - "3.7"
      - "3.6"
    dist: xenial
    sudo: true
    before_script:
      - sudo chmod +x ./src/test/compile-src.sh #Add permission to run script
      - python3.6 -m pip install pybuilder #For Build System
      - python3.7 -m pip install pyinstaller #For Creating Executable
    script:
      - ./src/test/compile-src.sh #Compile python files in /src
      - pyb install_dependencies #Install Build Dependencies
      - pyb #Build
    after_script:
      - cd ./src/main/python #Move adjacent to target script for executable
      - python3.7 -m PyInstaller GitUp.py --onefile #Create executable
      - cp ./gui/git_attributes.txt ./dist #The dist folder contains the executable, but also requires this .txt for deployment
      - ./dist/GitUp& PID=$!; sleep 5; kill $PID #Run the executable before we zip it to make sure it opens
      - mv dist GitUp #Rename folder to be zipped
      - zip -r GitUp.zip GitUp #Zip
      #- Deploy to dropbox
