matrix:
  include:
    language: python
    python: 3.6
    dist: xenial
    sudo: true
    before_script:
      - sudo chmod +x ./src/test/compile-src.sh
      - python3.6 -m pip install pybuilder
    script:
      - ./src/test/compile-src.sh
      - pyb install_dependencies
      - pyb
